### ISSUE TITLE
Some files seem to be missing

### ISSUE THREAD

**Issue by ajyoon** [LCagmac/NeoscoreII#1]
Hey there! I was trying to run this just now and ran into some difficulty. It seems like a few things aren't set up quite right:

- This code seems to assume it's placed in the neoscore repo `examples` directory, as it uses the `helpers` module. That module is really specific just to neoscore's internal examples, so I don't recommend using it. You probably just want to call `neoscore.show()` directly instead.
- This code also requires some static image assets (like `music.png`), again placed in neoscore's internal directory structure. I would recommend placing your assets directly in a folder in this repo instead.
- Also, it would be helpful to include a [`requirements.txt`](https://learnpython.com/blog/python-requirements-file/) file so we can easily download the required dependencies. I was able to work around this just by checking the code for what's being used, but it's a lot easier if we can `pip install -r requirements.txt`

**Comment by LCagmac** [comment]
Hi! Sorry about that! The images have been added and a requirements doc was added to the github page.

**Comment by ajyoon** [comment]
thanks! I had to rename the `Square.png` file to `square.png` (lowercase) to get this working, but otherwise I think I more or less got it. I wasn't able to get the keyboard input working because of the sudo stuff, but this looks really cool!

btw, in Python the requirements.txt file is actually a programmatic file specifying third party dependencies, not a narrative description of its dependencies. you can learn more about it over here https://learnpython.com/blog/python-requirements-file

**Comment by LCagmac** [comment]
Thanks! I will change the requirement document up
