### ISSUE TITLE
Why PyGame?

### ISSUE THREAD

**Issue by ajyoon** [LCagmac/NeoscoreII#2]
Reading through the code I was wondering - what's your use for pygame here? Is there a feature you need which it has and neoscore's interactive runtime doesn't? I know [at least key input should work](https://github.com/DigiScore/neoscore/discussions/52#discussioncomment-3059139) easily enough. I'm concerned you might run into trouble having a pygame and Qt runtime going simultaneously - Python's threading system really doesn't like when we try things like that.

**Comment by LCagmac** [comment]
At first it was just easier to use with my code, but I tried the keyboard library  and just had to use sudo in my terminal to use it with y'alls  ipython's live coding setup. The switch will make it easier to trigger changes in the animation with the keycodes. It is there now if you want to try it out.

**Comment by ajyoon** [comment]
Oh I see, I didn't realize the keyboard input libraries required sudo on linux, that's annoying (but makes sense from a security standpoint I guess). I'll look into supporting key/mouse input out of the box..

**Comment by ajyoon** [comment]
i'm tracking this improvement now at https://github.com/DigiScore/neoscore/issues/57 - should be able to get to it some time this week

**Comment by PludotGames** [comment]
Ive used it to make myself a video game but i think you can use it to make different interactive applications, Its a kind of game engine in the way that it renders you code in a windowed application
